export const entityDefinitions = {
  User: {
    required: ["email", "role"],
    schema: {
      email: { type: String, required: true, trim: true, lowercase: true },
      password_hash: { type: String, required: true, select: false },
      full_name: { type: String, trim: true, default: "" },
      role: { type: String, enum: ["admin", "user"], required: true, default: "user" },
      can_report_time: { type: Boolean, default: false },
      can_view_time_reports: { type: Boolean, default: false },
      can_manage_workplaces: { type: Boolean, default: false },
      is_active: { type: Boolean, default: true },
    },
    indexes: [{ fields: { email: 1 }, options: { unique: true } }],
  },
  Student: {
    required: ["full_name"],
    schema: {
      full_name: { type: String, required: true, trim: true },
      phone: { type: String, trim: true },
      cohort: { type: String, trim: true },
      free_day: {
        type: [{ type: String, enum: ["א", "ב", "ג", "ד", "ה"] }],
        default: null,
      },
      distance_status: {
        type: String,
        enum: ["קרוב", "רחוק", "אאא- לפני שיבוץ", "תתת - לא עובד", null],
      },
      is_active: { type: Boolean, default: true },
      forbidden_workplaces: [{ type: String }],
      notes: { type: String },
    },
  },
  Assignment: {
    required: ["date", "student_id", "workplace_id"],
    schema: {
      date: { type: String, required: true },
      student_id: { type: String, required: true },
      student_name: { type: String },
      workplace_id: { type: String, required: true },
      workplace_name: { type: String },
      role: { type: String },
      rate: { type: Number, default: 40 },
      hours: { type: Number, default: 4.5 },
      bonus: { type: Number },
      notes: { type: String },
    },
    indexes: [{ fields: { date: 1, student_id: 1 } }],
  },
  Vehicle: {
    required: ["name"],
    schema: {
      name: { type: String, required: true, trim: true },
      license_plate: { type: String, trim: true },
      insurance: { type: String },
      notes: { type: String },
    },
  },
  Role: {
    required: ["name"],
    schema: {
      name: { type: String, required: true, trim: true },
      description: { type: String },
      color: { type: String },
    },
  },
  Workplace: {
    required: ["name"],
    schema: {
      name: { type: String, required: true, trim: true },
      farm_name: { type: String },
      address: { type: String },
      company_id: { type: String },
      contact_phone: { type: String },
      accounting_phone: { type: String },
      accounting_email: { type: String },
    },
  },
  WorkplaceLogistics: {
    required: ["date", "workplace_id"],
    schema: {
      date: { type: String, required: true },
      workplace_id: { type: String, required: true },
      workplace_name: { type: String },
      driver_student_id: { type: String },
      driver_student_name: { type: String },
      vehicle_id: { type: String },
      vehicle_name: { type: String },
      vehicle_id_2: { type: String },
      vehicle_name_2: { type: String },
      vehicle_id_3: { type: String },
      vehicle_name_3: { type: String },
      exit_time: { type: String },
      notes: { type: String },
    },
    indexes: [{ fields: { date: 1, workplace_id: 1 } }],
  },
  PublishedSchedule: {
    required: ["date", "file_url"],
    schema: {
      date: { type: String, required: true },
      file_url: { type: String, required: true },
      snapshot: { type: Object },
    },
  },
  BackupSettings: {
    required: [],
    schema: {
      emails: [{ type: String }],
      last_backup_at: { type: Date },
      last_backup_filename: { type: String },
    },
  },
  IncomingSMS: {
    required: [],
    schema: {
      message: { type: String, default: "" },
      phone: { type: String, trim: true },
      sms_date: { type: String, trim: true },
      parsed_date: { type: String, trim: true },
      parsed_reason: { type: String, trim: true },
      parsed_student_name: { type: String, trim: true },
      status: {
        type: String,
        enum: ["ממתין", "אושר", "נדחה"],
        default: "ממתין",
      },
      notes: { type: String },
      student_id: { type: String },
      student_name: { type: String, trim: true },
    },
    indexes: [{ fields: { status: 1, created_date: -1 } }],
  },
  FarmerRequest: {
    required: ["date", "workplace_id"],
    schema: {
      date: { type: String, required: true },
      workplace_id: { type: String, required: true },
      workplace_name: { type: String, trim: true },
      requested_volunteers: { type: Number, default: null },
    },
    indexes: [{ fields: { date: 1 } }],
  },
  TimeReport: {
    required: ["date", "student_id", "workplace_id"],
    schema: {
      date: { type: String, required: true },
      student_id: { type: String, required: true },
      student_name: { type: String },
      workplace_id: { type: String, required: true },
      workplace_name: { type: String },
      start_time: { type: String },
      end_time: { type: String },
      status: {
        type: String,
        enum: ["ממתין", "אושר", "נדחה"],
        default: "ממתין",
      },
      notes: { type: String },
    },
    indexes: [{ fields: { date: 1, student_id: 1 } }],
  },
  AppSettings: {
    required: [],
    schema: {
      pricing_method: {
        type: String,
        enum: ["hourly", "daily"],
        default: "hourly",
      },
      default_rate: { type: Number },
      default_hours: { type: Number },
      default_daily_rate: { type: Number },
      hours_per_daily_unit: { type: Number },
      default_start_time: { type: String },
      default_end_time: { type: String },
    },
  },
};

export const entityNames = Object.keys(entityDefinitions);
